version: '3.8'

services:
  web:
    image: distillery-api
    container_name: distillery-api
    build:
      context: ./src/server/
      dockerfile: Dockerfile
    env_file:
      - ./src/server/.env
    ports:
      - 5000:5000
    volumes:
      - ./src/server/:/usr/src/app
    depends_on:
      - postgres

  postgres:
    container_name: distillery-db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=distillery-db
    volumes:
      - ./src/server/postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
