version: '3.8'

services:
  app:
    image: distillery-app
    container_name: distillery-app
    build:
      context: ./src/client/
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src/client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - web

  web:
    image: distillery-api
    container_name: distillery-api
    build:
      context: ./src/server/
      dockerfile: dev.Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./src/server:/usr/src/app
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: distillery-db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=distillery-db
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./src/server/postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  node_modules:
