version: '3.8'

services:
  app:
    image: distillery-app
    container_name: distillery-app
    build:
      context: ./src/client/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src/client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - web

  web:
    image: distillery-api
    container_name: distillery-api
    build:
      context: ./src/server/
      dockerfile: Dockerfile
    env_file:
      - ./src/server/.env
    ports:
      - 5000:5000
    volumes:
      - ./src/server:/usr/src/app
    depends_on:
      - postgres

  postgres:
    container_name: distillery-db
    image: postgres:alpine
    env_file:
      - ./src/server/.env
    volumes:
      - ./src/server/postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  node_modules:
